# Generated by Django 3.2.7 on 2021-09-12 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(max_length=1)),
                ('range1_min', models.IntegerField()),
                ('range1_max', models.IntegerField()),
                ('range2_min', models.IntegerField()),
                ('range2_max', models.IntegerField()),
                ('number_of_correct_answers', models.IntegerField(default=0)),
                ('number_of_wrong_answers', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GameAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_factor', models.IntegerField()),
                ('second_factor', models.IntegerField()),
                ('answer', models.IntegerField(null=True)),
                ('correct_answer', models.IntegerField()),
                ('was_this_answer_correct', models.BooleanField(null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='final_project_app.game')),
            ],
        ),
    ]
