# Generated by Django 2.2.6 on 2021-09-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_project_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_game_ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gameanswers',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
