# Generated by Django 2.2.6 on 2021-09-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_project_app', '0003_game_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(default='a', max_length=64),
            preserve_default=False,
        ),
    ]
